blank_issues_enabled: false
contact_links:
  - name: Extensions list
    url: https://tachiyomi.org/extensions
    about: List of all available extensions with download links.
  - name: Tachiyomi help website
    url: https://tachiyomi.org/help/
    about: Common questions are answered here.
  - name: Tachiyomi app GitHub repository
    url: https://github.com/tachiyomiorg/tachiyomi
    about: Issues about the app itself should be opened here instead.