name: 🧠 Meta feature request
description: Suggest improvements to the project
labels: [meta]
body:

  - type: markdown
    attributes:
      value: |
        To suggest a feature for Tachiyomi Extension, include a short but informative title above, and fill out the form below.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
          required: true
        - label: I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
          required: true
        - label: I have updated all installed extensions.
          required: true
        - label: I will fill the forms below with sufficient information.
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Describe why this should be added
      description: How is the expected behaviour of the proposed feature?
      placeholder: |
        Example:
          "It should work like this..."
    validations:
      required: true